export const ENEMIES = {
  // Acte 1 — Échauffement
  goblin: {
    id: 'goblin',
    name: 'GOBELIN',
    sprite: 'goblin',
    hp: 130,
    atkMin: 14,
    atkMax: 24,
    ai: 'goblin',
    exp: 20,
  },
  // Acte 2 — Première vraie résistance
  orc: {
    id: 'orc',
    name: 'ORC BERSERKER',
    sprite: 'orc',
    hp: 210,
    atkMin: 22,
    atkMax: 33,
    ai: 'orc',
    rageThreshold: 0.40,   // rage plus tôt
    rageAtkMult: 1.6,       // rage plus forte
    exp: 35,
  },
  // Acte 3 — Danger magique
  witch: {
    id: 'witch',
    name: 'SORCIÈRE DES CENDRES',
    sprite: 'witch',
    hp: 170,
    atkMin: 28,
    atkMax: 40,
    defPierce: 0.45,        // ignore presque la moitié de la DEF
    ai: 'witch',
    regenAmount: 18,         // régénération significative
    curseChance: 0.35,       // malédiction fréquente
    curseDuration: 3,        // dure plus longtemps
    curseDmgMult: 0.50,      // attaques héros à 50%
    exp: 50,
  },
  // Acte 4 — Double menace
  gnolls: {
    id: 'gnolls',
    name: 'FRÈRES GNOLLS',
    sprite: 'gnoll',
    multi: true,
    enemies: [
      { name: 'GNOLL ALPHA', hp: 120, atkMin: 18, atkMax: 28 },
      { name: 'GNOLL BETA',  hp: 110, atkMin: 15, atkMax: 24 },
    ],
    ai: 'gnolls',
    vengeanceAtkBonus: 20,   // vengeance dévastatrice
    exp: 70,
  },
  // Acte 5 — Boss final
  shadowLord: {
    id: 'shadowLord',
    name: 'SEIGNEUR DES OMBRES',
    sprite: 'shadowLord',
    hp: 340,
    atkMin: 36,
    atkMax: 52,
    ai: 'shadowLord',
    phase2Threshold: 170,    // phase 2 à 50% HP
    phase2AtkMult: 1.7,      // ATK ×1.7 en phase 2
    doubleHitChance: 0.55,
    doubleHitMult: 0.65,
    shieldBreakChance: 0.45,
    healBlockEvery: 2,
    exp: 115,
  },
  // ── Mine ────────────────────────────────────────────────────
  cave_bat: {
    id: 'cave_bat',
    name: 'NUÉE DE CHAUVES-SOURIS',
    sprite: 'cave_bat',
    multi: true,
    enemies: [
      { name: 'CHAUVE-SOURIS α', hp: 55, atkMin: 10, atkMax: 16 },
      { name: 'CHAUVE-SOURIS β', hp: 50, atkMin:  8, atkMax: 14 },
    ],
    ai: 'cave_bat',
    dodgeBonus: 0.18,
    exp: 30,
  },
  cave_dwarf: {
    id: 'cave_dwarf',
    name: 'NAIN DES MINES',
    sprite: 'cave_dwarf',
    hp: 145,
    atkMin: 16,
    atkMax: 24,
    ai: 'cave_dwarf',
    counterCycle: 3,
    counterReflect: 0.50,
    exp: 40,
  },
  cave_miner: {
    id: 'cave_miner',
    name: 'MINEUR EXPLOSIF',
    sprite: 'cave_miner',
    hp: 160,
    atkMin: 14,
    atkMax: 22,
    ai: 'cave_miner',
    explosionCountdown: 3,
    explosionDamage: 60,
    exp: 45,
  },
  cave_troll: {
    id: 'cave_troll',
    name: 'TROLL DES CAVERNES',
    sprite: 'cave_troll',
    hp: 240,
    atkMin: 20,
    atkMax: 32,
    ai: 'cave_troll',
    regenPerTurn: 12,
    heavyBlowCycle: 3,
    exp: 55,
  },
  cave_troll_king: {
    id: 'cave_troll_king',
    name: 'ROI TROLL',
    sprite: 'cave_troll_king',
    hp: 310,
    atkMin: 26,
    atkMax: 40,
    ai: 'cave_troll_king',
    regenPerTurn: 18,
    quakeCycle: 3,
    quakeDamage: 40,
    phase2Threshold: 155,
    phase2AtkMult: 1.5,
    exp: 75,
  },
  // ── Glacier ──────────────────────────────────────────────────
  frost_troll: {
    id: 'frost_troll',
    name: 'TROLL DU GIVRE',
    sprite: 'frost_troll',
    hp: 285,
    atkMin: 24,
    atkMax: 38,
    ai: 'frost_troll',
    regenPerTurn: 14,
    frostSmashCycle: 3,
    frostSmashDamage: 50,
    frozenDuration: 2,
    phase2Threshold: 142,
    phase2AtkMult: 1.45,
    exp: 88,
  },
  ice_witch: {
    id: 'ice_witch',
    name: 'SORCIÈRE DE GLACE',
    sprite: 'ice_witch',
    hp: 200,
    atkMin: 32,
    atkMax: 46,
    defPierce: 0.50,
    ai: 'ice_witch',
    blizzardChance: 0.35,
    blizzardDamage: 28,
    frozenDuration: 2,
    regenAmount: 15,
    regenChance: 0.30,
    exp: 95,
  },
  // ── Château hanté ────────────────────────────────────────────
  ghost_knight: {
    id: 'ghost_knight',
    name: 'CHEVALIER FANTÔME',
    sprite: 'ghost_knight',
    hp: 245,
    atkMin: 26,
    atkMax: 40,
    defPierce: 0.35,
    ai: 'ghost_knight',
    phaseEvadeChance: 0.30,
    hauntCycle: 3,
    curseDmgMult: 0.40,
    curseDuration: 1,
    phase2Threshold: 98,
    phase2AtkMult: 1.55,
    exp: 95,
  },
  vampire: {
    id: 'vampire',
    name: 'COMTE VAMPIRE',
    sprite: 'vampire',
    hp: 280,
    atkMin: 30,
    atkMax: 46,
    ai: 'vampire',
    bloodDrainCycle: 3,
    bloodDrainAmount: 35,
    bloodDrainHeal: 25,
    regenAmount: 12,
    batSwarmChance: 0.30,
    batSwarmMult: 0.60,
    exp: 105,
  },
  // ── Cité des Démons ──────────────────────────────────────────
  demon_warrior: {
    id: 'demon_warrior',
    name: 'GUERRIER DÉMON',
    sprite: 'demon_warrior',
    hp: 300,
    atkMin: 36,
    atkMax: 52,
    ai: 'demon_warrior',
    fireSlashCycle: 3,
    burnDamage: 12,
    burnDuration: 3,
    rageThreshold: 0.40,
    rageAtkMult: 1.6,
    exp: 110,
  },
  demon_lord: {
    id: 'demon_lord',
    name: 'SEIGNEUR DÉMON',
    sprite: 'demon_lord',
    hp: 420,
    atkMin: 42,
    atkMax: 62,
    defPierce: 0.35,
    ai: 'demon_lord',
    phase2Threshold: 210,
    phase2AtkMult: 1.75,
    hellfireCycle: 3,
    hellfireDamage: 70,
    burnDamage: 18,
    burnDuration: 3,
    doubleHitChance: 0.45,
    doubleHitMult: 0.65,
    curseChance: 0.25,
    curseDuration: 2,
    curseDmgMult: 0.55,
    shieldBreakChance: 0.40,
    exp: 150,
  },
  // ── Temple maudit ────────────────────────────────────────────
  cursed_knight: {
    id: 'cursed_knight',
    name: 'CHEVALIER MAUDIT',
    sprite: 'cursed_knight',
    hp: 225,
    atkMin: 24,
    atkMax: 36,
    ai: 'cursed_knight',
    shieldCrushCycle: 3,
    shieldCrushDamage: 45,
    rageThreshold: 0.35,
    rageAtkMult: 1.5,
    exp: 60,
  },
  // ── Jungle ───────────────────────────────────────────────────
  jungle_beast: {
    id: 'jungle_beast',
    name: 'BÊTE DE LA JUNGLE',
    sprite: 'jungle_beast',
    hp: 270,
    atkMin: 28,
    atkMax: 42,
    ai: 'jungle_beast',
    pounceCycle: 3,
    pounceHitMult: 0.70,
    frenzyThreshold: 0.40,
    frenzyAtkMult: 1.45,
    exp: 80,
  },
  // ── Catacombes ───────────────────────────────────────────────
  skeleton: {
    id: 'skeleton',
    name: 'SQUELETTE MAUDIT',
    sprite: 'skeleton',
    hp: 175,
    atkMin: 20,
    atkMax: 32,
    defPierce: 0.30,
    ai: 'skeleton',
    boneSpearCycle: 3,
    exp: 55,
  },
  lich: {
    id: 'lich',
    name: 'LICHE ANCIENNE',
    sprite: 'lich',
    hp: 210,
    atkMin: 32,
    atkMax: 48,
    defPierce: 0.55,
    ai: 'lich',
    soulDrainCycle: 3,
    soulDrainHeal: 30,
    curseChance: 0.30,
    curseDuration: 2,
    curseDmgMult: 0.55,
    exp: 90,
  },
  // ── Plage ────────────────────────────────────────────────────
  pirate_grunt: {
    id: 'pirate_grunt',
    name: 'BOUCANIER',
    sprite: 'pirate_grunt',
    hp: 155,
    atkMin: 18,
    atkMax: 28,
    ai: 'pirate_grunt',
    pillageAtkBonus: 8,
    pillageMaxStacks: 3,
    exp: 42,
  },
  pirate_crew: {
    id: 'pirate_crew',
    name: 'ÉQUIPAGE PIRATE',
    sprite: 'pirate_grunt',
    multi: true,
    enemies: [
      { name: 'CORSAIRE ROUGE', hp: 130, atkMin: 16, atkMax: 24 },
      { name: 'CORSAIRE NOIR',  hp: 125, atkMin: 16, atkMax: 24 },
    ],
    ai: 'pirate_crew',
    vengeanceAtkBonus: 20,
    exp: 58,
  },
  pirate_quartermaster: {
    id: 'pirate_quartermaster',
    name: 'QUARTIER-MAÎTRE',
    sprite: 'pirate_quartermaster',
    hp: 200,
    atkMin: 22,
    atkMax: 34,
    ai: 'pirate_quartermaster',
    poisonDamage: 8,
    exp: 62,
  },
  pirate_captain: {
    id: 'pirate_captain',
    name: 'CAPITAINE FLIBUSTIER',
    sprite: 'pirate_captain',
    hp: 230,
    atkMin: 24,
    atkMax: 36,
    ai: 'pirate_captain',
    cannonballCycle: 3,
    cannonballDamage: 55,
    exp: 70,
  },
};

export const BATTLE_SEQUENCE = ['goblin', 'orc', 'witch', 'gnolls', 'shadowLord'];
